### ISSUE TITLE
redis-cluster svc NodePort 

### ISSUE THREAD

**Issue by jicki** [ucloud/redis-cluster-operator#80]
How to create serivce  to a NodePort

**Comment by jiangjian0920** [comment]
Has the problem been solved

**Comment by jicki** [comment]
> Has the problem been solved

yes!

**Comment by jiangjian0920** [comment]
i want to know where to configure this parameter



---Original---
From: ***@***.***&gt;
Date: Tue, May 18, 2021 14:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ucloud/redis-cluster-operator] redis-cluster svc NodePort  (#80)




  
Has the problem been solved
  
yes!

**Comment by jicki** [comment]
> i want to know where to configure this parameter
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Tue, May 18, 2021 14:06 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [ucloud/redis-cluster-operator] redis-cluster svc NodePort (#80) Has the problem been solved yes! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

add new service  and type  NodePort 


呃 你是国人吗～ 我英语不太好的。 

其实就是添加一下新的 service 然后配置一个 NodePort 

但是其实 Redis 集群 你访问的时候 会跳转到内部的地址里面去

所以内部的 redis IP都需要外部能访问才可以配置外部访问地址

**Comment by jiangjian0920** [comment]
好的，我试试



---Original---
From: ***@***.***&gt;
Date: Wed, May 19, 2021 09:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ucloud/redis-cluster-operator] redis-cluster svc NodePort  (#80)




  
i want to know where to configure this parameter
 …
 ---Original--- From: @.&gt; Date: Tue, May 18, 2021 14:06 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [ucloud/redis-cluster-operator] redis-cluster svc NodePort (#80) Has the problem been solved yes! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
add new service  and type  NodePort
 
呃 你是国人吗～ 我英语不太好的。
 
其实就是添加一下新的 service 然后配置一个 NodePort
 
但是其实 Redis 集群 你访问的时候 会跳转到内部的地址里面去
 
所以内部的 redis IP都需要外部能访问才可以配置外部访问地址

**Comment by jiangjian0920** [comment]
你有试过跨集群连接吗，是不是不行



---Original---
From: ***@***.***&gt;
Date: Wed, May 19, 2021 09:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ucloud/redis-cluster-operator] redis-cluster svc NodePort  (#80)




  
i want to know where to configure this parameter
 …
 ---Original--- From: @.&gt; Date: Tue, May 18, 2021 14:06 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [ucloud/redis-cluster-operator] redis-cluster svc NodePort (#80) Has the problem been solved yes! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
add new service  and type  NodePort
 
呃 你是国人吗～ 我英语不太好的。
 
其实就是添加一下新的 service 然后配置一个 NodePort
 
但是其实 Redis 集群 你访问的时候 会跳转到内部的地址里面去
 
所以内部的 redis IP都需要外部能访问才可以配置外部访问地址

**Comment by jicki** [comment]
> 你有试过跨集群连接吗，是不是不行
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, May 19, 2021 09:08 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [ucloud/redis-cluster-operator] redis-cluster svc NodePort (#80) i want to know where to configure this parameter … ---Original--- From: @.&gt; Date: Tue, May 18, 2021 14:06 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [ucloud/redis-cluster-operator] redis-cluster svc NodePort (#80) Has the problem been solved yes! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. add new service and type NodePort 呃 你是国人吗～ 我英语不太好的。 其实就是添加一下新的 service 然后配置一个 NodePort 但是其实 Redis 集群 你访问的时候 会跳转到内部的地址里面去 所以内部的 redis IP都需要外部能访问才可以配置外部访问地址 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

不行～ 只在同一个集群中访问～甚至是同一个 namespaces 下～ 不然会跳转不过去~ 有点麻烦这个东西

**Comment by ztbill** [comment]
> > i want to know where to configure this parameter
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Tue, May 18, 2021 14:06 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [ucloud/redis-cluster-operator] redis-cluster svc NodePort (#80) Has the problem been solved yes! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> add new service and type NodePort
> 
> 呃 你是国人吗～ 我英语不太好的。
> 
> 其实就是添加一下新的 service 然后配置一个 NodePort
> 
> 但是其实 Redis 集群 你访问的时候 会跳转到内部的地址里面去
> 
> 所以内部的 redis IP都需要外部能访问才可以配置外部访问地址

你好，请问下使用了nodeport，但是redis cluster nodes任然使用的是podip无法从外部路由到此内部ip，你是如何解决的？能否给下代码片段或者思路
